version: "3.3"

services:
    nginx:
        image: nginx:alpine
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/nginx.crt:/etc/nginx/ssl/nginx.crt
        - ./nginx/nginx.key:/etc/nginx/ssl/nginx.key
        ports:
        - "443:443"
    minio:
        image: minio/minio
        environment: 
        - MINIO_ROOT_USER=<minio-user>
        - MINIO_ROOT_PASSWORD=<minio-password>
        - MINIO_REGION_NAME=<minio-region>
        volumes:
        - "/data/minio:/data"
        command: server /data

