name: deploy frontend to github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install and Build 🔧 Frontend
        run: |
          cd frontend
          npm install
          npm run build
      # - name: Install and Build 🔧 Storybook
      #   run: |
      #     cd frontend
      #     npm run build-storybook
      #     cp -r storybook-static ./build/storybook
      
      - name: Deploy
        uses: iotaledger/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./frontend/build
          cname: trees.einfachiota.de